name: SauceDemoTest
on:
  pull_request:
    branches: [ main ]

jobs:

  sauceDemoLogin:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o Projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -D"cucumber.filter.tags=@login"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução dos testes de login :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução dos testes de login :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQobWv5KNc4Tt0mNS5tWpHojJb5q2y_glZax8QwLe6g&s?size=48
          SLACK_MESSAGE: 'Falha na execução dos testes de login :rotating_light:'
          SLACK_TITLE: 'Falha na execução dos testes de login :rotating_light:'
          SLACK_USERNAME: FALHA

  sauceDemoAddProduct:
    runs-on: ubuntu-latest
    needs: sauceDemoLogin

    steps:
      - name: Clonar o Projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -D"cucumber.filter.tags=@add-product"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução dos testes de adicionar produto ao carrinho :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução dos testes de adicionar produto ao carrinho :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQobWv5KNc4Tt0mNS5tWpHojJb5q2y_glZax8QwLe6g&s?size=48
          SLACK_MESSAGE: 'Falha na execução dos testes de adicionar produto ao carrinho :rotating_light:'
          SLACK_TITLE: 'Falha na execução dos testes de adicionar produto ao carrinho :rotating_light:'
          SLACK_USERNAME: FALHA


  sauceDemoRemoveProduct:
    runs-on: ubuntu-latest
    needs: sauceDemoAddProduct
    name: sauceDemoRemoveProduct
    if: ${{ success() }}

    steps:
      - name: Clonar o Projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -D"cucumber.filter.tags=@remove-product"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução dos testes de remover produto do carrinho :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução dos testes de remover produto do carrinho :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQobWv5KNc4Tt0mNS5tWpHojJb5q2y_glZax8QwLe6g&s?size=48
          SLACK_MESSAGE: 'Falha na execução dos testes de remover produto do carrinho :rotating_light:'
          SLACK_TITLE: 'Falha na execução dos testes de remover produto do carrinho :rotating_light:'
          SLACK_USERNAME: FALHA

  sauceDemoCheckout:
    runs-on: ubuntu-latest
    needs: sauceDemoAddProduct

    steps:
      - name: Clonar o Projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -D"cucumber.filter.tags=@checkout"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução dos testes de checkout :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução dos testes de checkout :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQobWv5KNc4Tt0mNS5tWpHojJb5q2y_glZax8QwLe6g&s?size=48
          SLACK_MESSAGE: 'Falha na execução dos testes de checkout :rotating_light:'
          SLACK_TITLE: 'Falha na execução dos testes de checkout :rotating_light:'
          SLACK_USERNAME: FALHA